# Generated by Django 5.1.7 on 2025-03-11 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
