# Generated by Django 5.1.7 on 2025-03-15 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsApp", "0004_category_article_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsletter",
            name="approved",
        ),
        migrations.AddField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending Approval"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
